# Generated by Django 5.1.6 on 2026-03-07 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0002_addmembermoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmembermoney',
            name='date_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
