# Generated by Django 5.1.6 on 2026-02-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='dinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='lunch',
            field=models.IntegerField(default=0),
        ),
    ]
