# Generated by Django 5.1.6 on 2026-03-07 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bazar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_cost',
            name='date_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='extra_charge',
            name='date_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
