# Generated by Django 5.1.6 on 2026-03-09 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bazar', '0002_add_cost_date_time_extra_charge_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_cost',
            name='date_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
