# Generated by Django 5.1.6 on 2026-03-09 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bazar', '0003_alter_add_cost_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_charge',
            name='date_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
